### ISSUE TITLE
A problem about GPU memory

### ISSUE THREAD

**Issue by Yinyf0804** [ppengtang/pcl.pytorch#32]
Hi, Thanks for your great code. I have a problem about the GPU memory used.

I run the code on GTX 1080Ti. At the beginning of the training, the code uses about 7000+MiB memory, but it will gradully increases to 10000+MiB memory at about 800-1000 iter.  I am confused why the memory will change.

By the way, could you please tell me the memory used in your experiment?

Thank you!

**Comment by ppengtang** [comment]
Sorry I don't remember the exact memory cost in my experiments. But the memory cost increases after several training iterations makes sense. The reason is that, PCL takes all proposals of each image during training, and different images have different number of proposals so need different GPU memories. After several training iterations, it is very possible that we will pass an image with a huge number (like 4000+) of proposals through the network, which results in huge GPU memory costs.

**Comment by Yinyf0804** [comment]
Oh I see. Thanks for your reply!
